"""Paths and constants shared by the pipeline stages."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_CSV = ROOT / "data" / "ufc_fighters_enriched.csv"
SCHEMA_SQL = Path(__file__).with_name("schema.sql")
WAREHOUSE_DB = ROOT / "warehouse.db"          # git-ignored build artefact
QUALITY_REPORT = ROOT / "docs" / "DATA_QUALITY.md"

# Columns that are NOT loaded into the warehouse because they are not real observations.
# `foot` is generated by a seeded random rule in scripts/enrich_dataset.py (see
# data/data_dictionary.csv, source = "estimated"); foot_hand is built from it.
EXCLUDED_ESTIMATED_COLUMNS = ["foot", "foot_hand"]

VALID_STANCES = {"Orthodox", "Southpaw", "Switch"}
VALID_HANDS = {"Right", "Left"}
VALID_GENDERS = {"Men", "Women"}
VALID_STYLES = {"Striker", "Grappler", "All-rounder", "Not enough UFC data"}
