"""Render validation results to docs/DATA_QUALITY.md (deterministic: no timestamps)."""
from __future__ import annotations

import hashlib
from pathlib import Path

import pandas as pd

from .config import QUALITY_REPORT, SOURCE_CSV
from .validate import CheckResult, completeness, has_errors


def render(df: pd.DataFrame, results: list[CheckResult], source: Path | str = SOURCE_CSV) -> str:
    source = Path(source)
    digest = hashlib.sha256(source.read_bytes()).hexdigest()[:12] if source.exists() else "n/a"
    err = [r for r in results if r.severity == "error"]
    wrn = [r for r in results if r.severity == "warn"]
    lines = [
        "# Data quality report", "",
        "Generated by `python -m pipeline.run` (stage 2, `pipeline/validate.py`). "
        "Do not edit by hand; re-run the pipeline instead.", "",
        f"- Source: `data/{source.name}` (sha256 `{digest}...`)",
        f"- Rows: {len(df)}  |  Columns: {df.shape[1]}",
        f"- Error checks: {sum(r.passed for r in err)}/{len(err)} passed "
        f"({'load allowed' if not has_errors(results) else 'LOAD BLOCKED'})",
        f"- Warning checks: {sum(r.passed for r in wrn)}/{len(wrn)} clean "
        f"({sum(not r.passed for r in wrn)} with findings)", "",
        "Errors block the load into `warehouse.db`; warnings are reported and the load continues.", "",
        "## Error checks (block the load)", "",
        "| Check | Rule | Rows failing | Result |", "|---|---|---:|---|",
    ]
    for r in err:
        lines.append(f"| `{r.name}` | {r.description} | {r.failed} | {'PASS' if r.passed else 'FAIL'} |")
    lines += ["", "## Warnings (reported, do not block)", "",
              "| Check | Rule | Rows flagged | Examples |", "|---|---|---:|---|"]
    for r in wrn:
        ex = "; ".join(r.examples) if r.examples else ""
        lines.append(f"| `{r.name}` | {r.description} | {r.failed} | {ex} |")
    comp = completeness(df)
    lines += ["", "## Columns with missing values", ""]
    if comp.empty:
        lines.append("None.")
    else:
        lines += ["| Column | Missing | Completeness % |", "|---|---:|---:|"]
        lines += [f"| `{c}` | {int(r.missing)} | {r.completeness_pct} |" for c, r in comp.iterrows()]
    lines += ["", "Missing UFC stats mean the fighter has no matching UFCSTATS fight-level rows in the "
              "build inputs; they are loaded as NULL and never imputed.", ""]
    return "\n".join(lines)


def write(df, results, path: Path | str = QUALITY_REPORT, source: Path | str = SOURCE_CSV) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(df, results, source), encoding="utf-8")
    return path
